#!/bin/bash

FILE="bell_dist.txt";

MAX_CHARACTERS=20;
MIN_FREQ=5;
MAX_FREQ=50;
INCREMENT=5;

CURRENT_FREQ=$MIN_FREQ;
CURRENT_LINE="";

echo "" > $FILE;

for ((i = 0; i < MAX_CHARACTERS + 1; i++)); do

	echo "Current Frequency: $CURRENT_FREQ"

	if [[ CURRENT_FREQ == MAX_FREQ ]]; then
		INCREMENT=-5;
		echo "Switched to -5"
	elif [[ CURRENT_FREQ == MIN_FREQ ]]; then
		INCREMENT=5;
		echo "Switched to 5"
	fi

	for ((j = 0; j < CURRENT_FREQ; j++)); do
		CURRENT_LINE+="x";
	done

	echo $CURRENT_LINE > $FILE;
	
	CURRENT_LINE="";
	CURRENT_FREQ=$((CURRENT_FREQ + INCREMENT));

	echo "New Frequency: $CURRENT_FREQ"
done



